---

- name: install pip rhel 7
  command:
    chdir: /tmp
    cmd: python get-pip.py
    creates: /usr/bin/pip

- name: install required python libs rhel7
  pip:
    executable: /usr/bin/pip
    state: present
    name: 'docker-py'

- name: install docker
  yum:
    state: present
    name: docker
