# Licensed Materials - Property of IBM
# IBM Cloud private
# @ Copyright IBM Corp. 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

# A list of OpenShift nodes
cluster_nodes:
  master:
    - worker3.ndftest.os.fyre.ibm.com
    - worker4.ndftest.os.fyre.ibm.com
  proxy:
    - worker3.ndftest.os.fyre.ibm.com
    - worker4.ndftest.os.fyre.ibm.com
  management:
    - worker3.ndftest.os.fyre.ibm.com

storage_class: rook-ceph-cephfs-internal

## You can set different storage class for logging.
## By default it will use the value of storage_class.
# elasticsearch_storage_class: rook-ceph-cephfs-internal

default_admin_password: passw0rd
password_rules:
  - '^([a-zA-Z0-9-]{8,})$'
#   - '^([a-zA-Z0-9\-]{32,})$'

## You can disable following services if they are not needed
management_services:
  # Common services
  iam-policy-controller: enabled
  metering: enabled
  licensing: enabled
  monitoring: disabled
  nginx-ingress: disabled
  common-web-ui: enabled
  catalog-ui: enabled
  mcm-kui: disabled
  logging: disabled
  audit-logging: disabled
  system-healthcheck-service: disabled
  multitenancy-enforcement: disabled

