apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  namespace: openshift-storage
spec:
  channel: stable-4.3
  name: ocs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
