---
# tasks file for noi

- name: oc login
  k8s_auth:
    username: kubeadmin
    password: "{{k8sAdminPassword}}"
    host: "{{k8s_api}}"
    validate_certs: no
  register: login

- name: cloudctl login
  shell:
    cmd: "cloudctl login -a $(oc get routes -n kube-system icp-console -o jsonpath='{.spec.host}' --kubeconfig {{ kubeconfig }}) -u admin -p {{icp_password}} -n default --skip-ssl-validation"
  register: cloudctl
  changed_when: False

- name: cloudctl login result
  debug:
    msg: "{{cloudctl}}"
    verbosity: 1

- name: login info
  debug:
    msg: "{{login}}"
    verbosity: 1

- name: token
  debug:
    msg: "{{login.k8s_auth.api_key}}"
    verbosity: 1

- name: check if noi is already installed
  shell:
    cmd: helm list noi --tls
  register: helm_chart_noi

- import_tasks: install_noi.yml
  when:
    - "helm_chart_noi.stdout == ''"
